push
alloy-rs/core pull request #304
Opened 2023-09-25 20:24 UTC by supernovahs

Ref https://github.com/paradigmxyz/reth/pull/4758

2023-09-25 22:11 UTC, prestwich requested changes
good contribution, thanks. a few  changes :)

2023-09-25 22:11 UTC, prestwich commented on crates/primitives/src/utils.rs
> +pub fn hash_message<T: AsRef<[u8]>>(message: T) -> B256 {
can we prefix this with `eip191_` to match the eip712 methods in sol-types?

2023-09-25 22:11 UTC, prestwich commented on crates/primitives/src/utils.rs
> +    const PREFIX: &str = "\x19Ethereum Signed Message:\n";
move const out of function to module scope. Rename to `EIP191_PREFIX`

2023-09-25 22:11 UTC, prestwich commented on crates/primitives/src/utils.rs
> +}
please add the test from ethers-rs

```
// test vector taken from:
    // https://web3js.readthedocs.io/en/v1.2.2/web3-eth-accounts.html#hashmessage
    #[test]
    fn test_hash_message() {
        let hash = hash_message("Hello World");

        assert_eq!(
            hash,
            "a1de988600a42c4b4ab089b619297c17d53cffae5d5120d82d8a92d0bb3b78f2".parse().unwrap()
        );
    }
```

2023-09-26 11:26 UTC, DaniPopes approved these changes

2023-09-26 11:59 UTC, merged