feat: IntoLogData
alloy-rs/core pull request #666
Opened 2024-06-15 16:03 UTC by prestwich

## Motivation

Groundwork for https://github.com/alloy-rs/alloy/issues/623
Adding this conversion trait allows us to bound receipt log vectors in more meaningful ways

## Solution

Introduce trait for types which can be infallibly converted into LogData

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-06-17 11:17 UTC, mattsse approved these changes

2024-06-17 11:50 UTC, DaniPopes requested changes

2024-06-17 11:50 UTC, DaniPopes commented on crates/sol-macro-expander/src/expand/contract.rs
> +            let variants: Vec<_> = events.iter().map(e_name).collect();
```suggestion
            let variants = events.iter().map(e_name);
```

2024-06-17 11:50 UTC, DaniPopes commented on crates/sol-macro-expander/src/expand/contract.rs
> +                            alloy_sol_types::private::IntoLogData::to_log_data(inner),
```suggestion
                            Self::#variants(inner) =>
                            alloy_sol_types::private::IntoLogData::to_log_data(inner),
```

2024-06-17 11:50 UTC, DaniPopes commented on crates/sol-macro-expander/src/expand/contract.rs
> +                    fn into_log_data(self) -> alloy_sol_types::private::LogData {
```suggestion

                    fn into_log_data(self) -> alloy_sol_types::private::LogData {
```

2024-06-17 11:50 UTC, DaniPopes commented on crates/sol-macro-expander/src/expand/event.rs
> +                }
fmt

2024-06-18 11:05 UTC, DaniPopes approved these changes

2024-06-18 11:05 UTC, merged