feat(dyn-abi): support parse scientific number
alloy-rs/core pull request #835
Opened 2024-12-31 07:03 UTC by 9547

## Motivation

implement and close https://github.com/alloy-rs/core/issues/816

## Solution

## PR Checklist

- [x] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

2024-12-31 09:38 UTC, mattsse requested changes
style suggestion,

not familiar with the winnow api

2024-12-31 09:38 UTC, mattsse commented on crates/dyn-abi/src/coerce.rs
> +    if let Some(c) = input.chars().next() {
you can use let Some else return err notation here with next + filter

2024-12-31 13:34 UTC, DaniPopes commented on crates/dyn-abi/src/error.rs
> +    NegativeExponent(usize),
Should move this to the error in coerce.rs

2024-12-31 14:13 UTC, mattsse requested changes

2024-12-31 14:13 UTC, mattsse commented on crates/dyn-abi/src/coerce.rs
> +        Err(ErrMode::from_external_error(input, ErrorKind::Verify, Error::NegativeExponent(exp)))
this can be moved below L450

2025-01-01 00:57 UTC, 9547 commented on crates/dyn-abi/src/coerce.rs
> +        Err(ErrMode::from_external_error(input, ErrorKind::Verify, Error::NegativeExponent(exp)))
sounds good, thanks

2025-01-01 14:03 UTC, DaniPopes approved these changes
Thanks!

2025-01-01 14:41 UTC, merged